export enum RoutePathEnum {
  NONE = '',
  HOME = '/',
  SIGN_IN = '/signin',
  FORGET_PASSWORD = '/forgetpassword',
  ABOUT = '/about',
  BLOG = '/blog',
  BLOG_DETAIL = '/blog/[blogId]',
  PRODUCTS = '/prodcuts',
  PRIVACY_POLICY = '/privacypolicy',
  TERMS_OF_SERVICE = '/termsofservoce',
  HELP = '/help',
  MY_DOCUMENT = '/mydocument',
  NO_RESULT_FOUND = '/noresultfound',
  PROFILE = '/profile',
  ERROR_401 = '/401',
  ERROR_403 = '/403',
  ERROR_404 = '/404',
  ERROR_500 = '/500',
  NO_RESULT = '/noresultfound',
}
