import React from 'react';
import Head from 'next/head';

import { Container } from '@mui/material';

const Home = () => (
  <Container maxWidth="lg">
    <Head>
      <title>Common Credit Guy</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <h1>Welcome</h1>
    </main>
  </Container>
);

export default Home;
